// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package phonenumberutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.google.i18n.phonenumbers.Phonenumber.PhoneNumber;
import com.google.i18n.phonenumbers.PhoneNumberUtil;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Parse extends CustomJavaAction<IMendixObject>
{
	private java.lang.String InputPhoneNumber;
	private java.lang.String RegionCode;

	public Parse(IContext context, java.lang.String InputPhoneNumber, java.lang.String RegionCode)
	{
		super(context);
		this.InputPhoneNumber = InputPhoneNumber;
		this.RegionCode = RegionCode;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		PhoneNumberUtil pnu = PhoneNumberUtil.getInstance();
		PhoneNumber phoneNumber = pnu.parse(this.InputPhoneNumber, this.RegionCode);
		if (!(pnu.isValidNumber(phoneNumber))) {
			return null;
		}
		phonenumberutil.proxies.PhoneNumber MxPN = new phonenumberutil.proxies.PhoneNumber(this.getContext());
		MxPN.setCountryCode(phoneNumber.getCountryCode());
		MxPN.setExtension(phoneNumber.getExtension());
		MxPN.setNationalNumber(phoneNumber.getNationalNumber());
		MxPN.setNumberOfLeadingZeros(phoneNumber.getNumberOfLeadingZeros());
		MxPN.setPreferredDomesticCarriedCode(phoneNumber.getPreferredDomesticCarrierCode());
		MxPN.setRawInput(phoneNumber.getRawInput());
		return MxPN.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Parse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
